### ISSUE TITLE
Suggestion for scaffold

### ISSUE THREAD

**Issue by spacecatplayz** [7GrandDadPGN/VapeV4ForRoblox#1]
couple ideas for scaffold:
Buy blocks setting
extend scaffold

i mostly wanted to say buy blocks setting but extend scaffold also just came as an idea to me.

**Comment by 7GrandDadPGN** [comment]
Will add this, thanks!

**Comment by 7GrandDadPGN** [comment]
Scaffold Expand and Buy Blocks has been added!
