### ISSUE TITLE
add bee hack to vape? suggestion?

### ISSUE THREAD

**Issue by MoonSecV2** [7GrandDadPGN/VapeV4ForRoblox#12]
the bee collection remote can be called and give a bee regardless of bee id or anything theres no cooldown
op

**Comment by MoonSecV2** [comment]
is it in private lol
oops accidentally leaked method yikes!!!!

**Comment by DataM0del** [comment]
> e

![image](https://github.com/user-attachments/assets/0a7f7398-33c1-421e-848c-7e57a8e11cb4)
