### ISSUE TITLE
Added AimAssist to Universal and remove Discord Button (you deleted vape discord now)

### ISSUE THREAD

**Issue by NTDCore** [7GrandDadPGN/VapeV4ForRoblox#124]
I want Added AimAssist to Universal because it have other game that is use good assist to pvp yeah it my reason

**Comment by NTDCore** [comment]
if you added it, thank you xylex

**Comment by sstvskids** [comment]
add xylex sex

**Comment by magician69420** [comment]
i am agree because because everyone have bad aim and discord server is deleted

**Comment by 7GrandDadPGN** [comment]
I would possibly have to make a good aimassist for guns, the one in bedwars is used for swords, the discord button will be removed soon.

**Comment by NTDCore** [comment]
> I would possibly have to make a good aimassist for guns, the one in bedwars is used for swords, the discord button will be removed soon.

Thank you! xylex <3

**Comment by NTDCore** [comment]
also if you add now go to 6872274481.lua and remove aimassist options button
and TargetStrafe in Skywars VOXELS Remove it cuz it not work anymore

**Comment by NTDCore** [comment]
mean remove aimassist like you remove killaura in universal and make a killaura in 6872274481.lua

**Comment by hexahigh** [comment]
Why did you delete the discord server? And will you make a new one?

**Comment by NTDCore** [comment]
> Why did you delete the discord server? And will you make a new one?

he not make new one

**Comment by TheMagicPiston** [comment]
> Why did you delete the discord server? And will you make a new one?

he got mad that i leaked his feet pics 😎

**Comment by NTDCore** [comment]
> I would possibly have to make a good aimassist for guns, the one in bedwars is used for swords, the discord button will be removed soon.

you done yeet?

**Comment by 7GrandDadPGN** [comment]
sorry for the inactivity, I have a lot on my plate rn and I'm hoping to clear it all up soon
sometime in the future this idea will be implemented.

**Comment by NTDCore** [comment]
> sorry for the inactivity, I have a lot on my plate rn and I'm hoping to clear it all up soon sometime in the future this idea will be implemented.

that ok xylex i hope you did it ^^

**Comment by 7GrandDadPGN** [comment]
Working on vape now, just some general changes, the aimbot will prob be a hard one to implement.

**Comment by NTDCore** [comment]
> Working on vape v4 now (updated vape lite), just some general changes, the aimbot will prob be a hard one to implement.

sheesh

**Comment by uzisama22** [comment]
we cant download vape lite cuz the website download doesnt work
@7GrandDadPGN

**Comment by NTDCore** [comment]
when aimassist real

**Comment by NTDCore** [comment]
@7GrandDadPGN did you make this file???? it just random apearing in my vape folder even am not create that
![image](https://user-images.githubusercontent.com/102583640/230037422-a3e6621b-21d6-44d8-a1b9-5aa36356cc78.png)

**Comment by NTDCore** [comment]
reee

**Comment by 7GrandDadPGN** [comment]
> we cant download vape lite cuz the website download doesnt work @7GrandDadPGN

Fixed

**Comment by 7GrandDadPGN** [comment]
> reee

Really haven't gotten around to it sorry, also trying to think of how to properly do it without it feeling clunky

**Comment by NTDCore** [comment]
> > reee
> 
> Really haven't gotten around to it sorry, also trying to think of how to properly do it without it feeling clunky

ok lol that fine

**Comment by SnoopyOwner** [comment]
sex

**Comment by RealPacket** [comment]
> sex

haram

**Comment by obesttellez** [comment]
Discord is still up just check his videos on yt for new server

**Comment by NTDCore** [comment]
> Discord is still up just check his videos on yt for new server

brain? the first vape discord got deleted so i did this issues

**Comment by 7GrandDadPGN** [comment]
> > Discord is still up just check his videos on yt for new server
> 
> brain? the first vape discord got deleted so i did this issues

no there is a new announcements discord.

**Comment by 7GrandDadPGN** [comment]
wrong button

**Comment by AsteriskCodes** [comment]
hmm i guess this will be here forever now

**Comment by 7GrandDadPGN** [comment]
Thinking about this.

**Comment by 7GrandDadPGN** [comment]
Discontinued, I did try though dw.
