### ISSUE TITLE
Metal ESP and Autokit

### ISSUE THREAD

**Issue by YukileNeko** [7GrandDadPGN/VapeV4ForRoblox#129]
Metal Detector ESP does not work and is stuck at the top left hand corner of the screen. The autokit does not work compared to how it used to as it does not auto-collect any metal loot/drop.

**Comment by NTDCore** [comment]
cuz you dont have metal kit

**Comment by NekoAuf** [comment]
I do have metal kit, it just doesn't work otherwise.
