### ISSUE TITLE
Add support for Apocalypse Rising 2

### ISSUE THREAD

**Issue by rutheniumm** [7GrandDadPGN/VapeV4ForRoblox#134]
It would be nicei f you added support for AR2, if you want a example of a free hub that supports it thats decent, you can check this one out https://github.com/AlexR32/Parvus it is pretty decent but crashes alot for synapse. AR2 has an anti-cheat and it would be nice if you guys would figure out how to bypass it too.

**Comment by 7GrandDadPGN** [comment]
I had a disabler for that game, got boring after 4 days lol
