### ISSUE TITLE
Added Vape CustomColorGui

### ISSUE THREAD

**Issue by NTDCore** [7GrandDadPGN/VapeV4ForRoblox#141]
so i did this cuz am bored vape theme it nothing new so i want custom color gui because we can custom any color we want like white really blue really purple and more so yeah i hope you made it

**Comment by YZSomething** [comment]
real

**Comment by sstvskids** [comment]
Yeah

**Comment by GreenScreeenMan134** [comment]
could just edit the ui lib to do that

**Comment by MaguirePool** [comment]
you can choose custom colour + just use rainbow its better

**Comment by 7GrandDadPGN** [comment]
put on todo

**Comment by NTDCore** [comment]
> put on todo

TY!1!1!1, yay now it gonna have Vape White

**Comment by 7GrandDadPGN** [comment]
Added
