### ISSUE TITLE
whisper aimbot

### ISSUE THREAD

**Issue by rahhhhhhhh** [7GrandDadPGN/VapeV4ForRoblox#143]
make projectileaimbot work with the whisper shooty thing

**Comment by 7GrandDadPGN** [comment]
someday, dk but I'll try

**Comment by rahhhhhhhh** [comment]
> someday, dk but I'll try

ty bbg

**Comment by 7GrandDadPGN** [comment]
its been 10 years ⭐, I don't know if I'll ever get to this lol

**Comment by uturv** [comment]
> its been 10 years ⭐, I don't know if I'll ever get to this lol

lololol

**Comment by 7GrandDadPGN** [comment]
after 6 years, Implemented.
