### ISSUE TITLE
Profiles randomly stop working / get overwritten

### ISSUE THREAD

**Issue by centerepic** [7GrandDadPGN/VapeV4ForRoblox#149]
Was playing for a bit, when I joined a new match from another I noticed it didn't autoload my profile. I checked, and all my profiles were gone. Not sure what may be causing this, since my profile still seems to be there.
Although a while ago it just completely overwrote my configuration with {(some random float)}
![image](https://user-images.githubusercontent.com/83483477/234749225-92f43e4d-d537-43a4-8ce1-259cad711e63.png)

**Comment by MaguirePool** [comment]
ok now its happening always when i inject in lobby go to match execute boom settings ogne

**Comment by MaguirePool** [comment]
@7GrandDadPGN fix pls thx

**Comment by MaguirePool** [comment]
Happening most of the time now

**Comment by Roblox-Thot** [comment]
It would be nice if you guys said what you are using to run the script.

Makes it hard to debug when we aren't sure what you are using.

**Comment by MaguirePool** [comment]
KRNL i thought i dont need to mention because i already mentioned it in my previous posts

**Comment by 7GrandDadPGN** [comment]
Investigating

**Comment by 7GrandDadPGN** [comment]
Cannot replicate, please contact me on discord xylex#1364

**Comment by MaguirePool** [comment]
Yesterday it was working fine ill check today

**Comment by MaguirePool** [comment]
oops forgot about it anyway it works fine
