### ISSUE TITLE
anticheatbypass not working

### ISSUE THREAD

**Issue by iloverolboxhaxs** [7GrandDadPGN/VapeV4ForRoblox#15]
anticheatbypass is not working you can get stuck at wall or game just ignores you(no placing blocks no item pickup)

**Comment by Solibex** [comment]
KRNL?

**Comment by iloverolboxhaxs** [comment]
yes

**Comment by iloverolboxhaxs** [comment]
so?

**Comment by 7GrandDadPGN** [comment]
should be fixed in next update.

**Comment by 7GrandDadPGN** [comment]
make sure ur settings are not dumb aswell
42 speed
95 longjump speed
