### ISSUE TITLE
Not issue question

### ISSUE THREAD

**Issue by MaguirePool** [7GrandDadPGN/VapeV4ForRoblox#151]
How do i use search if the thing im searching for is in a folder?

**Comment by NTDCore** [comment]
> How do i use search if the thing im searching for is in a folder?

you mean search that in render?

**Comment by MaguirePool** [comment]
> > How do i use search if the thing im searching for is in a folder?
> 
> you mean search that in render?

yes

**Comment by NTDCore** [comment]
> > > How do i use search if the thing im searching for is in a folder?
> > 
> > 
> > you mean search that in render?
> 
> yes

RightClick on Search and type the part that you want to search or you can find it in dex

**Comment by MaguirePool** [comment]
ok
