### ISSUE TITLE
Vape is not saving when going into a game

### ISSUE THREAD

**Issue by Simonisnot** [7GrandDadPGN/VapeV4ForRoblox#157]
I've used vape v4 for roblox before but now it just seems to not save when I go into a game anymore I use mobile I switched my executors but nothing fixed it the only time the settings save is in the lobby I disabled Lobby checking that did not work and I don't use the settings often

**Comment by 7GrandDadPGN** [comment]
????????????????????

**Comment by Simonisnot** [comment]
Whenever I load into a Lobby the settings I put there will save but whenever I load into a game in bedwars it will go back to default

**Comment by 7GrandDadPGN** [comment]
cannot repro.
