### ISSUE TITLE
i cant open gui 

### ISSUE THREAD

**Issue by booa12** [7GrandDadPGN/VapeV4ForRoblox#159]
i press right sfiht it dosent open
i use fluxus
and i use microsoft version of roblox

**Comment by TheMagicPiston** [comment]
🧠 roblox microsoft app doesnt have rshift

**Comment by uzisama22** [comment]
HOW TO OPEN?
@TheMagicPiston

**Comment by Roblox-Thot** [comment]
You can open UI by running this **after** Vape loaded
You can also replace `Delete` with any [KeyCode](https://create.roblox.com/docs/reference/engine/enums/KeyCode) just don't use any "Right" keys
Then press what ever you set it to

```lua
shared.GuiLibrary["GUIKeybind"] = "Delete"
