### ISSUE TITLE
Make a logo that can open the gui / vapev4

### ISSUE THREAD

**Issue by Oogaboogaman21** [7GrandDadPGN/VapeV4ForRoblox#161]
New way to bypass byfron with fluxus in microsoft store roblox. But keybinds no work. So rightshift no work :c . Rightshift no work no way use vape :c . So pls make a button to open vape :D

**Comment by Roblox-Thot** [comment]
You can open UI by running this **after** Vape loaded
You can also replace `Delete` with any [KeyCode](https://create.roblox.com/docs/reference/engine/enums/KeyCode) just don't use any "Right" keys
Then press what ever you set it to

```lua
shared.GuiLibrary["GUIKeybind"] = "Delete"
```
Then it should be that key anytime you load vape
