### ISSUE TITLE
vape assets issue

### ISSUE THREAD

**Issue by NTDCore** [7GrandDadPGN/VapeV4ForRoblox#162]
so you just update assets vape right? so the reason is assets now can be gone so fix it

**Comment by Kyurem102** [comment]
Is it your executor by any chance?

**Comment by 7GrandDadPGN** [comment]
> assets now can be gone so fix it

that's _verrrry_ helpful, maybe give a bit more information like what you are using?
fluxus uwp, sw ios, and flux mobile should work fine.

**Comment by Kyurem102** [comment]
> > assets now can be gone so fix it
> 
> that's _verrrry_ helpful, maybe give a bit more information like what you are using? fluxus uwp, sw ios, and flux mobile should work fine.

It seems to work fine if it's using a key that uwp can register for gui keybind

**Comment by NTDCore** [comment]
> > assets now can be gone so fix it
> 
> that's _verrrry_ helpful, maybe give a bit more information like what you are using? fluxus uwp, sw ios, and flux mobile should work fine.

im using fluxus android

**Comment by NTDCore** [comment]
also xylex i cant contact you on discord now cuz you blocked me

**Comment by 31VS1** [comment]
and please fix Kill aura Ccashing Roblox executor fluxus PC
