### ISSUE TITLE
Vape independent issue

### ISSUE THREAD

**Issue by TweakinsStuff** [7GrandDadPGN/VapeV4ForRoblox#164]
Hey xylex when i try using you're wiki on custom modules and windows and some other stuff i tried making a new window but instead it comes up with an error saying "Incomplete statement: expected assignment or a function call" at first i thought wait i didnt put in the "shared.VapeManualLoad = true" I used it at the end still same error so i tried another thing which is an module that did nothing so Im hoping maybe you can fix the error and also this is my code "shared.VapeIndependent = true
shared.CustomSaveVape = "Stuff"
local uilib = loadstring(game:HttpGet("https://raw.githubusercontent.com/7GrandDadPGN/VapeV4ForRoblox/main/NewMainScript.lua", true))()

uilib["ObjectsThatCanBeSaved"]

local overlay = GuiLibrary.CreateCustomWindow({
    ["Name"] = "Other", 
    ["Icon"] = "vape/assets/TargetIcon1.png", -- currently you have to use vape assets for icons, this may change in the future
    ["IconSize"] = 16 -- size in width to not look ugly
})
overlay["Bypass"] = true -- making the window position save properly
--overlay.SetVisible(true) -- not a toggle, pass in true or false
-- you can put objects in
-- overlay.GetCustomChildren()

shared.VapeManualLoad = true"

**Comment by RealPacket** [comment]
use a code block, not that, Here's a example of a code block being used:

```lua
-- NOTE: this was modified to be less shitty and work the same.
-- don't use the `[]` indexer when possible, only for things that have invalid characters or start with numbers (e.x. things that start with numbers, non-ASCII things, etc...) in them should you use the `[]` indexer.
shared.VapeIndependent = true
shared.CustomSaveVape = "Stuff"
local uilib = loadstring(game:HttpGet("https://raw.githubusercontent.com/7GrandDadPGN/VapeV4ForRoblox/main/NewMainScript.lua", true))()

-- line below was commented due to it causing a syntax error.
-- uilib.ObjectsThatCanBeSaved

local overlay = GuiLibrary.CreateCustomWindow({
Name = "Other",
Icon = "vape/assets/TargetIcon1.png", -- currently you have to use vape assets for icons, this may change in the future
IconSize = 16 -- size in width to not look ugly
})
overlay.Bypass = true -- making the window position save properly
--overlay.SetVisible(true) -- not a toggle, pass in true or false
-- you can put objects in
-- overlay.GetCustomChildren()

shared.VapeManualLoad = true
```

**Comment by 7GrandDadPGN** [comment]
> use a code block, not that, Here's a example of a code block being used:
> 
> ```lua
> -- NOTE: this was modified to be less shitty and work the same.
> -- don't use the `[]` indexer when possible, only for things that have invalid characters or start with numbers (e.x. things that start with numbers, non-ASCII things, etc...) in them should you use the `[]` indexer.
> shared.VapeIndependent = true
> shared.CustomSaveVape = "Stuff"
> local GuiLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/7GrandDadPGN/VapeV4ForRoblox/main/NewMainScript.lua", true))()
> 
> -- line below was commented due to it causing a syntax error.
> -- GuiLib.ObjectsThatCanBeSaved
> 
> local overlay = GuiLib.CreateCustomWindow({
>   Name = "Other",
>   Icon = "vape/assets/TargetIcon1.png", -- currently you have to use vape assets for icons, this may change in the future
>   IconSize = 16 -- size in width to not look ugly
> })
> overlay.Bypass = true -- making the window position save properly
> --overlay.SetVisible(true) -- not a toggle, pass in true or false
> -- you can put objects in
> -- overlay.GetCustomChildren()
> 
> shared.VapeManualLoad = true
> ```

this tbh, my old example from a year ago is really bad, hopefully this help's with using vape independent.
