### ISSUE TITLE
Hi GrandDad! I know someone that is "Selling" a leaked "texture pack source" or "SRC" something i dont know. 

### ISSUE THREAD

**Issue by CrimsonfiedOfficial** [7GrandDadPGN/VapeV4ForRoblox#172]
I hope you can get back to me and get this user banned. You can get back to me with discord (Crimsonfied#0504)
Thanks.

**Comment by zephr1213** [comment]
Who is it??

**Comment by zephr1213** [comment]
What are they sellling?

**Comment by CrimsonfiedOfficial** [comment]
i'd rather speak to @7GrandDadPGN

**Comment by CrimsonfiedOfficial** [comment]
a leaked "texture pack source" or "SRC" something i dont know.
