### ISSUE TITLE
Fixed GrappleDisabler

### ISSUE THREAD

**Issue by NTDCore** [7GrandDadPGN/VapeV4ForRoblox#176]
Bedwars Update the The Code or Something idk but GrappleDisabler became Heatseeker

**Comment by NTDCore** [comment]
like this https://media.discordapp.net/attachments/973468748923166790/1111467453525012562/Roblox_2023-05-26-08-32-11.mp4

**Comment by atyanex** [comment]
he said he would fix it (idk)
