### ISSUE TITLE
long jump not work

### ISSUE THREAD

**Issue by glitch65** [7GrandDadPGN/VapeV4ForRoblox#182]
when I activate this function I just hover in place and can spin like a spinner if I press wasd 

executor Fluxus for uwp

**Comment by easyontop** [comment]
you need TNT / Fireball / Cannon / Yuzi / etc. to make it work.
Use electron if fluxus not working
https://ryos.lol/
fluxus is shit ngl it crashes more than electron

**Comment by RealPacket** [comment]
l0nGJuMp n0t w0rk!!
