### ISSUE TITLE
Combat section is not normaly working!

### ISSUE THREAD

**Issue by SharkySquare** [7GrandDadPGN/VapeV4ForRoblox#187]
In **combat** section i have only **spirnt**!!! In other sections i have not enough tabs, and i can't find public profiles!!
![explorer_ssi132wr54](https://github.com/7GrandDadPGN/VapeV4ForRoblox/assets/124304300/2c10e660-15dd-471e-bd5a-d4d3d799cd58)

**Comment by uzisama22** [comment]
you only have sprint since your in lobby

**Comment by uzisama22** [comment]
go into a game to see other options
