### ISSUE TITLE
Auto clicker Broken

### ISSUE THREAD

**Issue by Oogaboogaman21** [7GrandDadPGN/VapeV4ForRoblox#195]
This was happenning in skull mode too, but now happening in every game please fix. (Season 8 bug)

**Comment by Oogaboogaman21** [comment]
Tell me when fixed or never gonna be fixed

**Comment by Markerlmaoz** [comment]
Just use a actual autoclicker you fucking moron

**Comment by Oogaboogaman21** [comment]
> Just use a actual autoclicker you fucking moron

Hmm interesting, I forgot there are also other features not working like auto buy and stuff. And also, the built in Vape v4 auto clicker is just more convenient, thank you for the idea thought :)

**Comment by 7GrandDadPGN** [comment]
should be fixed.

**Comment by Oogaboogaman21** [comment]
> should be fixed, dk about autobuy

TYSM THIS IS A GREAT FIX TO ALL THE CLOSET CHEATERS :D

**Comment by Oogaboogaman21** [comment]
forget all I said, autoclicker still broken
