### ISSUE TITLE
Vape TargetHUD

### ISSUE THREAD

**Issue by iraqicat** [7GrandDadPGN/VapeV4ForRoblox#198]
The gaps between the handsquares aren't equal (6872274481.lua line ~2250), should be:

handsquare.Position = UDim2.new(0, 72, 0, 44) --as it should be

helmetsquare.Position = UDim2.new(0, 100, 0, 44) --also as it should be

chestplatesquare.Position = UDim2.new(0, 128, 0, 44) --changed from 0,127,0,44 to 0,128,0,44

bootssquare.Position = UDim2.new(0, 156, 0, 44) --changed from 0,155,0,44, to 0,156,0,44

uselesssquare.Position = UDim2.new(0, 184, 0, 44) --changed from 0,182,0,44 to 0,184,0,44

the entire file (originally from commit 7341d9c6a908e84261f4f23c0f3f2e1046ad2a7c, 5am GMT +00:00 7/4/2023) is here (if you're just gonna drag and drop it):
[6872274481.lua.md] (https://github.com/7GrandDadPGN/VapeV4ForRoblox/files/11945706/6872274481.lua.md)

from this:
[image] (https://github.com/7GrandDadPGN/VapeV4ForRoblox/assets/135523806/2268cc56-b2c0-4aa1-89da-6f82c1e94e90)
to this:
[image] (https://github.com/7GrandDadPGN/VapeV4ForRoblox/assets/135523806/78c714b4-848b-4e39-b918-1118de6569f2)
(perfectionist moment)

if you intended this please let me know

**Comment by NTDCore** [comment]
it look same

**Comment by iraqicat** [comment]
@NTDCore > it look same

put the images side by side, look at the item(sword,bow,armor) frames, first one has uneven gaps, second one does.

**Comment by 7GrandDadPGN** [comment]
vape design tm, this isn't a bug.
