### ISSUE TITLE
Still autoclicker

### ISSUE THREAD

**Issue by Oogaboogaman21** [7GrandDadPGN/VapeV4ForRoblox#200]
Autoclicker still not fixed I just only tested in a custom match, I does not work in the real game. Autoclicker also does not work in third person even in custom match. (I tried fixing by enabling or disabling certain Modules but that did not work).

**Comment by Oogaboogaman21** [comment]
Autoclicker also does not work in third person even in custom match

**Comment by Bolawa09** [comment]
yep I also tested it out and it didn't work

**Comment by AsteriskCodes** [comment]
It's now resolved ✅

**Comment by Oogaboogaman21** [comment]
Yes
