### ISSUE TITLE
Discord Invite Invalid

### ISSUE THREAD

**Issue by OmniKingThe1st** [7GrandDadPGN/VapeV4ForRoblox#202]
The discord join link doesn't work

I typed "vapev4forroblox" but it said its invalid or incorrect.
also if you click the discord icon it closes ROBLOX after 3 seconds

**Comment by OmniKingThe1st** [comment]
It did say new discord server

**Comment by P0ngHG** [comment]
Here the new invite for the announcement server https://discord.gg/735YZhxTHf

**Comment by OmniKingThe1st** [comment]
> Here the new invite for the announcement server https://discord.gg/735YZhxTHf

Thx
