### ISSUE TITLE
Vape private

### ISSUE THREAD

**Issue by Oogaboogaman21** [7GrandDadPGN/VapeV4ForRoblox#209]
Hey xylex, I just got a question for you: who can use vape private? Because today I was closet hacking on my main and then a person in my game said w twice with a tag "Vape private". He was in a game of duels. So please tell me the people that are allowed to use vape private. (I also got a jumpscare after i won the game)

**Comment by Oogaboogaman21** [comment]
Also please respond and don't leave me on red.

**Comment by 7GrandDadPGN** [comment]
I'll leave you with a purple close mark instead :D

**Comment by Oogaboogaman21** [comment]
> I'll leave you with a purple close mark instead :D

I'm 100% gonna get banned on my main

**Comment by Oogaboogaman21** [comment]
> Hey xylex, I just got a question for you: who can use vape private? Because today I was closet hacking on my main and then a person in my game said w twice with a tag "Vape private". He was in a game of duels. So please tell me the people that are allowed to use vape private. (I also got a jumpscare after i won the game)

Also I'm sorry for my bad grammer as I mean't if vape private was leaked or so what
