### ISSUE TITLE
Vape private No bad grammer verison (I think)

### ISSUE THREAD

**Issue by Oogaboogaman21** [7GrandDadPGN/VapeV4ForRoblox#210]
I'm sorry for my previous issue request, I do have bad grammer. What I mean't was actually if vape private was leaked.
This only reason I'm bothering you with this is because I'm very afraid if my main account is going to get possibly banned because of the incident. 

Leave a Yes or No if vape private is leaked or not.
If you close this issue that would mean a no for me. (This option is for your convenience)
Thank you for your time!

**Comment by Oogaboogaman21** [comment]
I think the reason I have bad grammer is actually because I'm only 12 years old..

**Comment by Roblox-Thot** [comment]
Vape Private can't be "leaked" since it works is they whitelist each account they use.

There isn't really any way for them to ban your Roblox account at most you could be banned from BedWars. but vape users can't directly ban or "hack" your account.

**Comment by 7GrandDadPGN** [comment]
^^  A good explanation I don't think I would be able to write

In my terms I'd just say stupidity but above's better.

**Comment by Oogaboogaman21** [comment]
> Vape Private can't be "leaked" since it works is they whitelist each account they use.
> 
> There isn't really any way for them to ban your Roblox account at most you could be banned from BedWars. but vape users can't directly ban or "hack" your account.
> 
> The only thing that could be "leaked" are modules but even then you should be fine since Xylex doesn't want to add vape private commands to allow real banning of Vape users

Yep i understand I was just worried that random trolls would send a screenshot of me using vape to bedwars mods ty!

**Comment by Oogaboogaman21** [comment]
> ^^ A good explanation I don't think I would be able to write
> 
> In my terms I'd just say stupidity but above's better.

Understandable
