### ISSUE TITLE
schematicas?

### ISSUE THREAD

**Issue by MrGoopyDrawers** [7GrandDadPGN/VapeV4ForRoblox#218]
just asking for like a tutorial on how to make one, or maybe just sending a file of a schematica i can use so i can break it down.

**Comment by 7GrandDadPGN** [comment]
schematica's are kinda dead, after the rewrite I'll release the files for them.

**Comment by BeastGB** [comment]
here's a template at least. https://www.mediafire.com/file/3kg139xd09aomv0/vape.rar/file

put it in the workspace folder of your executor

**Comment by MrGoopyDrawers** [comment]
where are the schematics in that file?
