### ISSUE TITLE
Vape Lite on UWP

### ISSUE THREAD

**Issue by cringclosetcheater** [7GrandDadPGN/VapeV4ForRoblox#221]
if possible, make vape lite work on uwp

**Comment by Roblox-Thot** [comment]
Vape Lite uses a websocket to talk to the game and UWP blocks localhost websockets as of right now.  So the chance of V.L. being fixed is slim right now.


So it would need to be rewritten or Fluxus/whatever would need to add support for it

![image](https://github.com/7GrandDadPGN/VapeV4ForRoblox/assets/67937010/87750aa9-1b25-4b57-8567-52ac3b9d4de7)

**Comment by 7GrandDadPGN** [comment]
I tried it a bit ago, according to someone it worked on fluxus, dk about other executors,
