### ISSUE TITLE
No tutorial on how to make custom modules

### ISSUE THREAD

**Issue by RileyReid-EterniumConfig** [7GrandDadPGN/VapeV4ForRoblox#235]
make a tutorial/gitbook please

**Comment by Roblox-Thot** [comment]
I'm just going to respond for him (so you dont have to wait 2+ days <sub>kek</sub>)


But the most he will probably do is link you to the [docs](https://github.com/7GrandDadPGN/VapeV4ForRoblox/wiki/Documentation)

**Comment by RileyReid-EterniumConfig** [comment]
oh my thank you
