### ISSUE TITLE
LongJump suggestion

### ISSUE THREAD

**Issue by AsteriskCodes** [7GrandDadPGN/VapeV4ForRoblox#247]
When enabling LongJump, place down a **Gunpowder Barrel** and hit the barrel, making you zoom across long distances.

**Comment by 7GrandDadPGN** [comment]
> When enabling LongJump, place down a **Gunpowder Barrel** and hit the barrel, making you zoom across long distances.

Will add, thank you.

**Comment by 7GrandDadPGN** [comment]
Implemented, thank you for the suggestion!

**Comment by Silentboy152** [comment]
maybe you should add a thing that get you to level 50 in the battle pass

**Comment by McpvYeye** [comment]
Add a 6ix9ine Long jump !!!!!!!!! and a Monitor module like the chair ez
