### ISSUE TITLE
Fluxus not loading vape correctly

### ISSUE THREAD

**Issue by sstvskids** [7GrandDadPGN/VapeV4ForRoblox#248]
Fluxus doesn't load Vape correctly, and as a result other executors which use the Fluxus API (they skidded fluxus's api) have to also not load Vape correctly.

I've had to use other executors like KRNL and electron.

**Comment by TheMagicPiston** [comment]
skill issue

**Comment by Roblox-Thot** [comment]
skill issue

**Comment by xMintix** [comment]
skill issue also fluxus is just gay so stp

**Comment by AsteriskCodes** [comment]
skill issue

**Comment by 7GrandDadPGN** [comment]
Using fluxus fine, Skill issue.
