### ISSUE TITLE
Tool outlines

### ISSUE THREAD

**Issue by gamingware** [7GrandDadPGN/VapeV4ForRoblox#249]
For example, let's say a rainbow sword outline. I think it would be good for visuals!

**Comment by 7GrandDadPGN** [comment]
Possibility, Will investigate.

**Comment by gamingware** [comment]
Thank you.

**Comment by 7GrandDadPGN** [comment]
To be frank I couldn't figure out a way to do it (no I'm not using highlights), so atleast for now Denied.

**Comment by gamingware** [comment]
Alright. Thanks for trying!

**Comment by P996Lazer69** [comment]
i dont see why you would need this, but whatever
