### ISSUE TITLE
Suggestion: TargetHUD

### ISSUE THREAD

**Issue by Ayazerzurum2** [7GrandDadPGN/VapeV4ForRoblox#25]
TargetHUD
Example: (Rise Client stronk)
![image](https://user-images.githubusercontent.com/67198542/161987596-0480531a-80bb-4e40-be0f-0a2f58586d8b.png)
![image](https://user-images.githubusercontent.com/67198542/161987729-34e50875-f1e8-4605-8b3a-4d43484827cf.png)

**Comment by 7GrandDadPGN** [comment]
ever heard of target info in overlays?

**Comment by Ayazerzurum2** [comment]
Thats a design suggestion, Im already aware this exists.
