### ISSUE TITLE
R.I.P VAPE V4

### ISSUE THREAD

**Issue by RealPacket** [7GrandDadPGN/VapeV4ForRoblox#257]
![It's joever](https://github.com/7GrandDadPGN/VapeV4ForRoblox/assets/107498533/9676e078-df5b-4491-a6c2-b2ff5191c3c6)
:(

**Comment by RealPacket** [comment]
I have a local copy of Vape V4's source code in case the repository gets wiped (and I may continue vape if I want, not sure about my motivation on that though).

**Comment by Pave58** [comment]
:(

**Comment by asfsnfskjsfjdgkjgfhfjhfjhfsjhjfjfh** [comment]
I have the entire vape file so i can continue it if i want, along with a 100 speed scythe disabler

**Comment by asfsnfskjsfjdgkjgfhfjhfjhfsjhjfjfh** [comment]
Its not over yet, Fluxus will probably start a fight of titans

**Comment by 7GrandDadPGN** [comment]
legit don't care anymore, have fun skids
