### ISSUE TITLE
What happened to projectile Aura

### ISSUE THREAD

**Issue by xybytz** [7GrandDadPGN/VapeV4ForRoblox#275]
Yeah what happened to it

**Comment by Astonlix** [comment]
Yea what happened to it

**Comment by Roblox-Thot** [comment]
If i remember it was patched a while ago

**Comment by xybytz** [comment]
other vape configs have it tho

**Comment by Roblox-Thot** [comment]
idk then ![](https://cdn.discordapp.com/emojis/1124026226735054848.webp?size=24&quality=lossless)

**Comment by 7GrandDadPGN** [comment]
Implemented in the rewrite.
