### ISSUE TITLE
anti voidware owner (add this to files to prevent him from using it)

### ISSUE THREAD

**Issue by GalaxywareForRoblox** [7GrandDadPGN/VapeV4ForRoblox#293]
if lplr.Name == "coolgu_790" and lplr.UserId == 7348956404 then
    lplr:Kick("fuck off and stop pasting fucking retard")
end

**Comment by 7GrandDadPGN** [comment]
lplr.Name check 💀

**Comment by starsdotspace** [comment]
> lplr.Name check 💀

that's his user

**Comment by 7GrandDadPGN** [comment]
> > lplr.Name check 💀
> 
> that's his user

that's not the point, the point is why have a name check if you already have a userid check 💀

**Comment by starsdotspace** [comment]
> > > lplr.Name check 💀
> > 
> > 
> > that's his user
> 
> that's not the point, the point is why have a name check if you already have a userid check 💀

idk 🤷
