### ISSUE TITLE
Request : Rageblade on respawn

### ISSUE THREAD

**Issue by idk-pixel** [7GrandDadPGN/VapeV4ForRoblox#42]
We could implement this by look in the script from the item shop and do it. The item is located in game.ReplicatedStorage.Items.rageblade 
I hope that helped maybe implement it 
Thanks

**Comment by idk-pixel** [comment]
Also if it helps every time you swithc an item it switches the item in the explorer 2 in your hotbar idk how to make it go in the hotbar tho

**Comment by idk-pixel** [comment]
Update 3 : i figured out there is an inventoryfolder in every player

**Comment by Yayyyyaiwh** [comment]
> We could implement this by look in the script from the item shop and do it. The item is located in game.ReplicatedStorage.Items.rageblade I hope that helped maybe implement it Thanks

What do I do with that
