### ISSUE TITLE
Why did you commit leave from discord

### ISSUE THREAD

**Issue by 0W0Pumpkin** [7GrandDadPGN/VapeV4ForRoblox#5]
Hey grand, why did you leave the discord for vape?

**Comment by 7GrandDadPGN** [comment]
Discord is causing me stress, I'll still update vape.

**Comment by 0W0Pumpkin** [comment]
sure, sleepy, me and ct will take care of the discord server

**Comment by EthanMcDonagh** [comment]
Hey, grand, I'm experienced with Lua, Python, CSS & HTML.
I would like to help with Vape, please let me know if I can help 🙂
