### ISSUE TITLE
Text GUI background looks offset 

### ISSUE THREAD

**Issue by S0wwn** [7GrandDadPGN/VapeV4ForRoblox#51]
The Text GUI background looks broken with higher windows interface scale.
![image](https://user-images.githubusercontent.com/106026079/184318330-13e1e712-c3c3-4ff5-b476-2bca8b2ebd26.png)
How to replicate:
Go to windows settings > Display Settings > Change the scale to 125% or higher.
![image](https://user-images.githubusercontent.com/106026079/184318582-57d2eb01-9066-4370-b4f7-6b327c71085e.png)

**Comment by Oofility** [comment]
I'm having the same issues with 100%, the bg is just bigger than the text.

**Comment by 7GrandDadPGN** [comment]
bad monitor issue, fix never.
