### ISSUE TITLE
Sliders with decimals: when being set to a decimal, it will seem to divide it by 10.

### ISSUE THREAD

**Issue by joeengo** [7GrandDadPGN/VapeV4ForRoblox#67]
found this on anygame.lua:
using speed mode tp:
setting delay slider:
try setting delay to 0.1 with the text box, and it will be set to 0.01, same with 0.25, 0.2, ect...

video:
[https://i.gyazo.com/14b60c3c2e1eaf3d81c0cf4461d219e0.mp4](url)

**Comment by 7GrandDadPGN** [comment]
Will add a compensation for setting a value with decimal mode
