### ISSUE TITLE
Image not load

### ISSUE THREAD

**Issue by XBlueSkyCC** [7GrandDadPGN/VapeV4ForRoblox#71]
I don't know if this vape issues today every icon is not show

![image](https://user-images.githubusercontent.com/115792463/197155226-5a179f27-f463-46c3-b7aa-4e4488806308.png)

**Comment by XBlueSkyCC** [comment]
Nvm. it work after i reinstall windows

**Comment by LvoeHanyaz** [comment]
How to solve it
