### ISSUE TITLE
Suggestion: Slime Block Flight

### ISSUE THREAD

**Issue by yeeterlol** [7GrandDadPGN/VapeV4ForRoblox#9]
Slime blocks for some reason bypass the anticheat for a little bit, I have tried this out myself. It seems like it bypasses for a little bit. It's also really cheap costing about 24 iron, cheaper than TNT. This would be the perfect idea if we could find a bypass.

**Comment by 7GrandDadPGN** [comment]
Does not seem like enough time to fly with, Hopefully in the future I can find a method for it.
